name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    runs-on: windows-latest  # Use a Windows runner to build .NET projects

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Specify your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e 's,refs/tags/v,,')
          dotnet pack --configuration Release --no-build /p:Version=$VERSION --output ./nupkg

      - name: Publish Nuget Packages
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: ./nupkg
        continue-on-error: true  # Continue even if the push fails
        if: github.ref == 'refs/heads/main'  # Ensure this only runs on pushes to main
