name: Publish DocFX Documentation

on:
  push:
    tags:
      - 'd*'
  
permissions:
  actions: read
  pages: write
  id-token: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use a Windows runner to build .NET projects

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Set the version required by your DocFX project

    - name: Install DocFX
      run: dotnet tool update -g docfx

    - name: Build documentation
      run: docfx docfx.json
      working-directory: ./Documentation

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: './Documentation/_site'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
